Refactor Jenkins build job for cleaner syntax

diff --git a/jenkins-build-job b/jenkins-build-job
--- a/jenkins-build-job
+++ b/jenkins-build-job
@@ -11,16 +11,13 @@ pipeline {
         JAVA_HOME = '/usr/lib/jvm/java-21-openjdk-amd64'
         PATH = "${JAVA_HOME}/bin:${PATH}"
 
-        // AWS ECR Details
         AWS_ACCOUNT_ID = '246005668592'
         AWS_REGION = 'eu-north-1'
         ECR_REPO_NAME = 'my-maven-app-chart'
         ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
 
-        // DockerHub Image (your Spring Boot app)
         DOCKER_IMAGE = "aslahea/springboot-maven-app"
 
-        // Sonar
         SONAR_PROJECT_KEY = 'com.mycompany.app:springboot-maven-app'
     }
 
@@ -37,17 +34,13 @@ pipeline {
 
         stage('Maven Build') {
             steps {
-                sh '''
-                    mvn -B clean package -DskipTests
-                '''
+                sh 'mvn -B clean package -DskipTests'
             }
         }
 
         stage('Unit Test') {
             steps {
-                sh '''
-                    mvn test || true
-                '''
+                sh 'mvn test || true'
                 junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'
             }
         }
@@ -56,11 +49,11 @@ pipeline {
             steps {
                 withSonarQubeEnv('sonar') {
                     withCredentials([string(credentialsId: 'sonar-token', variable: 'TOKEN')]) {
-                        sh '''
-                            mvn sonar:sonar \
-                              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
-                              -Dsonar.login=${TOKEN}
-                        '''
+                        sh """
+                          mvn sonar:sonar \
+                            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
+                            -Dsonar.login=${TOKEN}
+                        """
                     }
                 }
             }
@@ -110,9 +103,16 @@ pipeline {
         stage('Update Helm Chart & Package') {
             steps {
                 dir('helm-chart') {
+
+                    script {
+                        CHART_VERSION = "0.${BUILD_NUMBER}.0"
+                    }
+
                     sh """
-                        sed -i 's|tag:.*|tag: "${BUILD_NUMBER}"|' values.yaml
+                        sed -i 's/^version:.*/version: ${CHART_VERSION}/' Chart.yaml
+
                         sed -i 's|repository:.*|repository: "${DOCKER_IMAGE}"|' values.yaml
+                        sed -i 's|tag:.*|tag: "${BUILD_NUMBER}"|' values.yaml
 
                         helm package .
                     """
@@ -124,28 +124,17 @@ pipeline {
 
         stage('Push Helm Chart to AWS ECR') {
             steps {
-                withCredentials([usernamePassword(credentialsId: 'aws-ecr-creds',
-                        usernameVariable: 'AWS_ACCESS_KEY_ID',
-                        passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
-        
+                withAWS(credentials: 'aws-ecr-creds', region: 'eu-north-1') {
+
                     sh '''
-                        # Configure AWS
-                        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
-                        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
-                        aws configure set default.region eu-north-1
-        
-                        # Login HELM to ECR
                         aws ecr get-login-password --region eu-north-1 \
                           | helm registry login --username AWS --password-stdin $ECR_REGISTRY
-        
+
                         cd helm-chart
-        
-                        # Auto-detect packaged .tgz file
-                        CHART=$(ls *-0.1.0.tgz | head -n 1)
-        
+
+                        CHART=$(ls *.tgz | head -n 1)
                         echo "Pushing chart: $CHART"
-        
-                        # IMPORTANT: Push only to registry root, NOT repo name
+
                         helm push $CHART oci://$ECR_REGISTRY/
                     '''
                 }
@@ -165,29 +154,17 @@ pipeline {
 
     post {
         success {
-            echo ' Pipeline completed successfully!'
-            sendEmailNotification(
-                currentBuild.currentResult,
-                [:]
-            )
+            echo 'Pipeline completed successfully!'
+            sendEmailNotification(currentBuild.currentResult, [:])
         }
-        
         failure {
-            echo ' Pipeline failed!'
-            sendEmailNotification(
-                currentBuild.currentResult,
-                [:]
-            )
+            echo 'Pipeline failed!'
+            sendEmailNotification(currentBuild.currentResult, [:])
         }
-    
         aborted {
-            echo ' Pipeline aborted!'
-            sendEmailNotification(
-                currentBuild.currentResult,
-                [:]
-            )
+            echo 'Pipeline aborted!'
+            sendEmailNotification(currentBuild.currentResult, [:])
         }
-    
         always {
             cleanWs()
         }
